# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/aws/aws-sdk-go";
    fetch = {
      type = "git";
      url = "https://github.com/aws/aws-sdk-go";
      rev = "2669c2336f87952c54c236e2fecfab3331176c79";
      sha256 = "0zz0cbrkcvj76pch747n9vrg7bi3jbx5896migcacyy8vazskbkv";
    };
  }
  {
    goPackagePath = "github.com/stretchr/testify";
    fetch = {
      type = "git";
      url = "https://github.com/stretchr/testify";
      rev = "2402e8e7a02fc811447d11f881aa9746cdc57983";
      sha256 = "01qaz781cvrv3h1428xqq8knf5ahdcj93m5k9dnivg2hcrlnqibj";
    };
  }
  {
    goPackagePath = "github.com/smartystreets/goconvey";
    fetch = {
      type = "git";
      url = "https://github.com/smartystreets/goconvey";
      rev = "3bd662eac601ad6436e64776af2e112069eb2edc";
      sha256 = "0zj7n92pp6lbmb28bww32n73jivningbp1fzzdnzc3yiv1a551s6";
    };
  }
  {
    goPackagePath = "github.com/jtolds/gls";
    fetch = {
      type = "git";
      url = "https://github.com/jtolds/gls";
      rev = "bb0351aa7eb6f322f32667d51375f26a2bca6628";
      sha256 = "09wd68ms4zp1fg7a540h559ls6vjgvh96w3hqgamilz5wggzqivh";
    };
  }
  {
    goPackagePath = "github.com/smartystreets/assertions";
    fetch = {
      type = "git";
      url = "https://github.com/smartystreets/assertions";
      rev = "26acb9229f421449ac63d014995b282d59261a8b";
      sha256 = "0nd68177yag49akdz7q9yydar46skq693jyq1f83l9vhgbwhwqwb";
    };
  }
  {
    goPackagePath = "github.com/golang/lint";
    fetch = {
        type = "git";
        url = "https://github.com/golang/lint";
        rev = "5295072ea38460cda1ff822cf6d30a7bf64329bd";
        sha256 = "1q21ll8ip9zgdc9vqmad96dv39swch2zwkar840yk9ydbv46sbyp";
    };
  }
]
