# This file was generated by go2nix.
[
  {
    goPackagePath = "github.com/aws/aws-sdk-go";
    fetch = {
      type = "git";
      url = "https://github.com/aws/aws-sdk-go";
      rev = "2669c2336f87952c54c236e2fecfab3331176c79";
      sha256 = "0zz0cbrkcvj76pch747n9vrg7bi3jbx5896migcacyy8vazskbkv";
    };
  }
]
